"""add_demos_table

Revision ID: 01145cfc6361
Revises: 8be7181ca40e
Create Date: 2026-03-31 00:29:37.503889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01145cfc6361'
down_revision: Union[str, Sequence[str], None] = '8be7181ca40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prospect_name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('target_description', sa.Text(), nullable=True),
    sa.Column('requester_email', sa.String(), nullable=True),
    sa.Column('requester_phone', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('leads_found', sa.Integer(), nullable=True),
    sa.Column('leads_verified', sa.Integer(), nullable=True),
    sa.Column('messages_generated', sa.Integer(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('report_viewed', sa.Boolean(), nullable=True),
    sa.Column('report_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('converted_to_paid', sa.Boolean(), nullable=True),
    sa.Column('demo_client_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demos')
    # ### end Alembic commands ###
