"""add_quality_logs

Revision ID: 06f088b91424
Revises: 1397a1f8af9f
Create Date: 2026-03-29 11:11:59.128035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f088b91424'
down_revision: Union[str, Sequence[str], None] = '1397a1f8af9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'agent_job_items', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'agent_jobs', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'leads', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'message_log', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'scraped_sources', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def upgrade() -> None:
    op.create_table('quality_logs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('client_id', sa.String(), nullable=True),
        sa.Column('lead_id', sa.String(), nullable=True),
        sa.Column('job_id', sa.String(), nullable=True),
        sa.Column('channel', sa.String(), nullable=True),
        sa.Column('passed', sa.Boolean(), nullable=True),
        sa.Column('passed_after_regen', sa.Boolean(), nullable=True),
        sa.Column('failed_permanently', sa.Boolean(), nullable=True),
        sa.Column('quality_score', sa.Float(), nullable=True),
        sa.Column('issues_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    op.drop_table('quality_logs')