"""add clients multi-tenant

Revision ID: 6eecf3438806
Revises: 514d263a4464
Create Date: 2026-03-28 10:54:48.454957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eecf3438806'
down_revision: Union[str, Sequence[str], None] = '514d263a4464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('icp_config', sa.JSON(), nullable=True),
    sa.Column('tone_config', sa.JSON(), nullable=True),
    sa.Column('wa_number', sa.String(), nullable=True),
    sa.Column('email_domain', sa.String(), nullable=True),
    sa.Column('plan_tier', sa.String(), nullable=True),
    sa.Column('monthly_lead_cap', sa.Integer(), nullable=True),
    sa.Column('monthly_email_cap', sa.Integer(), nullable=True),
    sa.Column('monthly_wa_cap', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('festival_blackout_dates', sa.JSON(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_job_items', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'agent_job_items', 'clients', ['client_id'], ['id'])
    op.add_column('agent_jobs', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'agent_jobs', 'clients', ['client_id'], ['id'])
    op.add_column('campaigns', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'clients', ['client_id'], ['id'])
    op.add_column('conversations', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'clients', ['client_id'], ['id'])
    op.add_column('leads', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'leads', 'clients', ['client_id'], ['id'])
    op.add_column('message_log', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'message_log', 'clients', ['client_id'], ['id'])
    op.add_column('scraped_sources', sa.Column('client_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'scraped_sources', 'clients', ['client_id'], ['id'])
    op.add_column('users', sa.Column('client_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    op.drop_column('users', 'client_id')
    op.drop_constraint(None, 'scraped_sources', type_='foreignkey')
    op.drop_column('scraped_sources', 'client_id')
    op.drop_constraint(None, 'message_log', type_='foreignkey')
    op.drop_column('message_log', 'client_id')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'client_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'client_id')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'client_id')
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_column('agent_jobs', 'client_id')
    op.drop_constraint(None, 'agent_job_items', type_='foreignkey')
    op.drop_column('agent_job_items', 'client_id')
    op.drop_table('clients')
    # ### end Alembic commands ###
