"""add ai_usage table

Revision ID: a95566cba2be
Revises: b4edd18f69e6
Create Date: 2026-03-28 12:34:23.348205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95566cba2be'
down_revision: Union[str, Sequence[str], None] = 'b4edd18f69e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('task_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'agent_job_items', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'agent_jobs', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'conversations', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'leads', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'message_log', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'scraped_sources', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'users', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'scraped_sources', type_='foreignkey')
    op.drop_constraint(None, 'message_log', type_='foreignkey')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'agent_jobs', type_='foreignkey')
    op.drop_constraint(None, 'agent_job_items', type_='foreignkey')
    op.drop_table('ai_usage')
    # ### end Alembic commands ###
