"""add_whitelabel_apikey_webhooks

Revision ID: ac3c68189cd5
Revises: 3aac3d414bac
Create Date: 2026-03-31 02:29:36.560253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac3c68189cd5'
down_revision: Union[str, Sequence[str], None] = '3aac3d414bac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # client_webhooks already created by Base.metadata.create_all — skip
    op.add_column('clients', sa.Column('brand_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('brand_logo_url', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('brand_color', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('brand_email_footer', sa.Text(), nullable=True))
    op.add_column('clients', sa.Column('white_label_enabled', sa.Boolean(), nullable=True))
    op.add_column('clients', sa.Column('api_key_hash', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('api_key_prefix', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'api_key_prefix')
    op.drop_column('clients', 'api_key_hash')
    op.drop_column('clients', 'white_label_enabled')
    op.drop_column('clients', 'brand_email_footer')
    op.drop_column('clients', 'brand_color')
    op.drop_column('clients', 'brand_logo_url')
    op.drop_column('clients', 'brand_name')
    op.drop_table('client_webhooks')
    # ### end Alembic commands ###
