"""add_wa_consent_fields

Revision ID: daa261a53ff1
Revises: 3c9b9c4f0667
Create Date: 2026-03-28 18:21:46.808390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daa261a53ff1'
down_revision: Union[str, Sequence[str], None] = '3c9b9c4f0667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('wa_consent', sa.Boolean(), nullable=True))
    op.add_column('leads', sa.Column('wa_consent_date', sa.DateTime(), nullable=True))
    op.add_column('leads', sa.Column('wa_consent_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'wa_consent_source')
    op.drop_column('leads', 'wa_consent_date')
    op.drop_column('leads', 'wa_consent')
    # ### end Alembic commands ###
